import type { EmailPayloads, EmailTemplate } from "@/lib/email-core";

/**
 * One realistic payload per template. Two consumers: the vitest render walk
 * (every template must render from its sample) and /admin/emails, whose
 * Preview and "send me a test" use exactly these. Keeping them in one pure
 * module means a template added without a sample fails the test AND is
 * missing from the admin picker — the mapped type below is what enforces it.
 */
export const EMAIL_SAMPLES: { [T in EmailTemplate]: EmailPayloads[T] } = {
  purchase_receipt: {
    planName: "Annual",
    examName: "PLAB 1",
    amountLabel: "$144.00 USD",
    accessUntil: "2027-09-09T23:59:59Z",
    paypalOrderId: "ORDER-1",
  },
  org_purchase_receipt: {
    orgName: "Springfield General",
    planName: "Org 90",
    examName: null,
    amountLabel: "$900.00 USD",
    accessUntil: "2027-09-09T23:59:59Z",
    paypalOrderId: "ORDER-2",
  },
  refund_recorded: {
    refundLabel: "$10.00 USD",
    totalRefundedLabel: "$10.00 USD",
    amountLabel: "$144.00 USD",
    accessWithdrawn: false,
    paypalOrderId: "ORDER-1",
  },
  payment_reversed: {
    kind: "reversed",
    amountLabel: "$144.00 USD",
    paypalOrderId: "ORDER-1",
  },
  access_expiring: {
    examName: "PLAB 1",
    endsAt: "2026-09-16T23:59:59Z",
    daysLeft: 7,
    renewPath: "/checkout/plan-1?exam=exam-1",
  },
  org_access_expiring: {
    orgId: "org-1",
    orgName: "Springfield General",
    examName: "PLAB 1",
    endsAt: "2026-09-10T23:59:59Z",
    daysLeft: 1,
  },
  org_invite: {
    orgName: "Springfield General",
    inviterName: "Dr <b>Hibbert</b>",
    role: "member",
    acceptPath: "/org/join/invite-1",
    expiresAt: "2026-09-23T00:00:00Z",
  },
  org_member_joined: {
    orgId: "org-1",
    orgName: "Springfield General",
    memberName: "Lisa",
    role: "member",
  },
  org_member_removed: { orgName: "Springfield General" },
  org_member_removed_notice: {
    orgId: "org-1",
    orgName: "Springfield General",
    memberName: "Bart",
    removedByName: "Dr Hibbert",
  },
  org_role_changed: { orgName: "Springfield General", role: "admin" },
  assignment_created: {
    orgName: "Springfield General",
    title: "Cardiology week 3",
    dueAt: "2026-09-12T23:59:59Z",
    questionCount: 40,
    mode: "exam",
  },
  assignment_due_soon: {
    orgName: "Springfield General",
    title: "Cardiology week 3",
    dueAt: "2026-09-12T23:59:59Z",
  },
  assignment_overdue: {
    orgName: "Springfield General",
    title: "Cardiology week 3",
    dueAt: "2026-09-08T23:59:59Z",
  },
  assignment_summary: {
    orgId: "org-1",
    orgName: "Springfield General",
    title: "Cardiology week 3",
    dueAt: "2026-09-08T23:59:59Z",
    targeted: 12,
    completed: 9,
    late: 2,
    meanPct: 71,
    notFinished: ["Bart", "Nelson"],
    notFinishedMore: 1,
  },
  certificate_issued: {
    courseTitle: "ECG basics",
    credentialName: "Dr Julius Hibbert",
    issuedAt: "2026-09-09T12:00:00Z",
    code: "CME-ABCDE-FGHIJ",
    verifyPath: "/verify/CME-ABCDE-FGHIJ",
    certificatesPath: "/cme/certificates",
  },
  report_resolved: {
    count: 2,
    resolution: "fixed",
    stems: ["A 45-year-old man presents with…", "Which of the following…"],
  },
  org_question_reported: {
    orgId: "org-1",
    orgName: "Springfield General",
    stem: "A 45-year-old man presents with…",
    category: "wrong_key",
    reportsPath: "/org/content/reports",
  },
  weekly_digest: {
    weekLabel: "31 Aug – 6 Sept",
    attempts: 120,
    correct: 84,
    accuracyPct: 70,
    streak: 4,
    weakSubjects: [{ name: "Nephrology", accuracyPct: 42 }],
    hasPlan: true,
  },
  admin_contact_message: {
    messageId: "msg-1",
    name: "Marge Bouvier",
    email: "marge@example.com",
    subject: "Institution pricing",
    excerpt:
      "Hello — we run a 60-seat residency programme and would like to know whether you offer institutional pricing and a sitting-date report…",
    messagesPath: "/admin/messages",
  },
  admin_question_reported: {
    stem: "A 45-year-old man presents with…",
    category: "wrong_key",
    examName: "PLAB 1",
    subjectName: "Cardiology",
    openReports: 3,
    reportsPath: "/admin/questions/reports",
  },
  admin_review_submitted: {
    reviewId: "rev-1",
    rating: 5,
    displayName: "Lisa S.",
    examName: "PLAB 1",
    verifiedPurchase: true,
    body: "The timed mocks were the closest thing to the real exam I found. Passed first time.",
    pendingReviews: 2,
    reviewsPath: "/admin/reviews",
  },
  admin_daily_digest: {
    dayLabel: "9 September 2026",
    newMessages: 2,
    openMessages: 3,
    newReports: 5,
    openReportQuestions: 4,
    pendingReviews: 1,
  },
  admin_import_finished: {
    examName: "PLAB 1",
    fileName: "plab1-cardiology.xlsx",
    imported: 180,
    skipped: 3,
    errorRows: 2,
    images: 14,
    createdSpecialties: 0,
    createdSubjects: 2,
    questionsPath: "/admin/questions",
  },
  admin_failure_alert: {
    kind: "osce_grading",
    failures: 7,
    calls: 31,
    windowHours: 24,
    threshold: 5,
    logPath: "/admin/osce",
  },
  admin_role_changed: {
    targetName: "Lisa Simpson",
    targetEmail: "lisa@example.com",
    before: "student",
    after: "admin",
    actorName: "Dr Hibbert",
    usersPath: "/admin/users/user-1",
  },
};
